# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs: 
  matlab: mathworks/matlab@0.7.1

jobs:
  build:
    machine:
      image: 'ubuntu-2004:202111-02'
    steps:
      - checkout
      - matlab/install
      - matlab/run-tests:
          test-results-junit: test-results/matlab/results.xml
      - store_test_results:
          path: test-results
workflows:
  build:
    jobs:
      - build
